version: '3.1'
services:

    # Application container
    dotnet:
        image: microsoft/dotnet
        environment:
          PORT: 8080
        volumes:
          - ./:/server/http
        links:
            - mysql
        ports:
          - "8080:8080"

    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        environment:
            LC_ALL: C.UTF-8
            MYSQL_ROOT_PASSWORD: 12345678
